### PR TITLE
fix: order of events on events subpage

### LINKED ISSUE #26: Change order of events
Currently on the events subpage, the table of upcoming events is ordered like this: distant future before near future. **It should be the other way around**.

(See also the homepage where events are ordered according to the correct pattern.)

### PR DESCRIPTION
**Pull request by dnsos**
This PR is a quickfix for changing the order of upcoming events on the events subpage.

The upcoming events are now sorted according to this pattern: near future before distant future.

Fixes #26

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
@dnsos Could be done like mentioned here https://stackoverflow.com/a/48136902/1770432

**Comment by dnsos** [comment]
@fabianmoronzirfas now this is done using the Vue Mixin pattern.

File: pages/all_events_en.vue [hunk 1]
```diff
@@ -139,10 +142,11 @@
                     this.data.push(obj);
                 })
 
-                this.data = this.data.sort((a,b) => { return new Date(b.date) - new Date(a.date) });
-
                 this.dataUpcoming = this.filterData(this.data, true);
                 this.dataPast = this.filterData(this.data, false);
+
+                this.dataUpcoming = this.sortDatesChronologically(this.dataUpcoming);
```
Comment (fabianmoronzirfas) [inline pages/all_events_en.vue:148]:
```js
this.dataUpcoming = this.filterData(this.data, true).sort(this.sortDatesChronologically);
this.dataPast = this.filterData(this.data, false).sort(this.sortDatesReverseChronologically);
```

No need for the reassignment. You should be able to pass in the function to `Array.sort`. But this is up to you
